# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - compatriots-abroad-app

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install and build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: npm install and build backend
      run: |
        cd backend
        npm install
        npm run build

    - name: create bundle
      run: |
        mkdir bundle/frontend
        cp -r frontend/.nuxt/* bundle/frontend
        mkdir bundle/backend
        cp -r backend/dist/* bundle/backend
        cp backend/package.json bundle/backend
        cd bundle/backend
        npm install --only=prod

    - name: zip bundle
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r bundle.zip bundle

    - name: Upload zipped bundle for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: bundle
        path: bundle.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'compatriots-abroad-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f030976c6d7740c39778b96440d5507f }}
        package: .